<?php

namespace AppBundle\Repository;

/**
 * AbstactUsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbstactUsersRepository extends \Doctrine\ORM\EntityRepository
{
}
